# Generated by Django 4.2.20 on 2025-03-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('order_time', models.DateTimeField(verbose_name='Ordered At')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('product_price', models.IntegerField(default=100, verbose_name='Product Price')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_unit_quantity', models.IntegerField(default=0, verbose_name='Number of items')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.order')),
                ('order_unit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.product')),
            ],
        ),
    ]
