# Generated by Django 4.2.20 on 2025-03-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order_unit',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order_unit',
            old_name='order_unit_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order_unit',
            old_name='order_unit_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
    ]
