# Generated by Django 4.2.20 on 2025-03-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_order_name_order_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_unit',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_unit',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_Unit',
        ),
    ]
